export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_NEW_USER = 'ADD_NEW_USER';
export const ADD_EXISTING_USER = 'ADD_EXISTING_USER';

export const ADD_HEALTH_DETAILS = 'ADD_HEALTH_DETAILS';
export const ADD_MACRO_DETAILS = 'ADD_MACRO_DETAILS';
export const ADD_WEIGHT_LOG = 'ADD_WEIGHT_LOG';